add_newline = true
scan_timeout = 10

# for performance profiling: uncomment and run `starship timings`
# [custom]

[character]
success_symbol = "[❯](bold #00afff)"
error_symbol = "[❯](bold red)"

[username]
disabled = true

[hostname]
ssh_only = true
disabled = false

[directory]
truncation_length = 0
truncate_to_repo = false
style = "bold #00afff"

[git_branch]
format = "[$branch]($style) "
style = "#5fd7ff"

[git_status]
style = "#767676"

[cmd_duration]
disabled = true

[ruby]
format = "[$version]($style) "

[docker_context]
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true

[openstack]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[lua]
disabled = true
